spring.application.name=demo

app.secret_key=${SECRET_KEY}
app.random_key=${RANDOM_KEY}
app.secret_var=${SECRET_VAR}

spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.url=jdbc:mariadb://localhost:3306/test
spring.datasource.username=root
spring.datasource.password=bc2025ia